#!/usr/bin/env python3
"""
Ensures _version.py exists for the shm_function_selector extension.
This file is auto-generated but sometimes missing in fresh installations.
"""

import os
import sys

def ensure_version_file():
    """Create _version.py if it doesn't exist."""
    version_file = os.path.join(os.path.dirname(__file__), "shm_function_selector", "_version.py")
    
    if not os.path.exists(version_file):
        print(f"⚠️  Creating missing _version.py at {version_file}")
        os.makedirs(os.path.dirname(version_file), exist_ok=True)
        
        with open(version_file, 'w') as f:
            f.write('# This file is auto-generated by Hatchling. As such, do not:\n')
            f.write('#   - modify\n')
            f.write('#   - track in version control e.g. be sure to add to .gitignore\n')
            f.write('__version__ = VERSION = "0.1.0"\n')
        
        print(f"✅ Created {version_file}")
    else:
        print(f"✅ _version.py already exists at {version_file}")

if __name__ == "__main__":
    ensure_version_file()