blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/ebpfly/shm/blob/main/README.md
    about: Check the documentation first
  - name: Discussions
    url: https://github.com/ebpfly/shm/discussions
    about: For general questions and discussions about SHMTools